export const COUNTRIES = [
  'Kazakhstan',
  'United States',
  'China',
  'India',
  'Germany',
  'France',
  'Italy',
  'Spain',
  'United Kingdom',
  'Canada',
  'Brazil',
  'Mexico',
  'Japan',
  'South Korea',
  'Turkey',
  'Iran',
  'Iraq',
  'Ukraine',
  'Poland',
  'Sweden',
  'Russia',
  'Norway',
  'Uzbekistan',
  'Finland',
  'Netherlands',
  'Switzerland',
  'Australia',
  'New Zealand',
  'Egypt',
  'South Africa',
  'Argentina',
  'Chile',
  'Colombia',
  'Saudi Arabia',
  'United Arab Emirates',
  'Pakistan',
  'Thailand',
  'Vietnam',
];

export type Country = (typeof COUNTRIES)[number];
